// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// #HerdrInput is the `herdr` verb's plugin_input: the method name plus its
// method-exclusive modifiers.
type HerdrInput struct {
	// method — the herdr verb method name (the verb's PRIMARY input field, so
	// `herdr: ping` desugars to {method: "ping"}).
	Method string `json:"method"`

	// workspace — workspace ID filter for tab-list / pane-list.
	Workspace string `json:"workspace,omitempty"`

	// pane — the pane ID for pane-wait-output.
	Pane string `json:"pane,omitempty"`

	// agent — the agent name or pane ID for agent-wait / agent-prompt.
	Agent string `json:"agent,omitempty"`

	// text — the prompt text for agent-prompt.
	Text string `json:"text,omitempty"`

	// match — literal substring for pane-wait-output (mutually exclusive with regex).
	Match string `json:"match,omitempty"`

	// regex — Rust regular expression for pane-wait-output (mutually exclusive with match).
	Regex string `json:"regex,omitempty"`

	// source — terminal read source, CLI spelling (recent-unwrapped maps to the
	// wire's recent_unwrapped). Default: recent.
	Source string `json:"source,omitempty"`

	// until — one agent lifecycle state for agent-wait (defaults: idle, done, blocked).
	Until string `json:"until,omitempty"`
}
